### ISSUE TITLE
[Question] WebServices methods

### ISSUE THREAD

**Issue by JustDevZero** [ddiazpinto/python-redsys#4]
Hi!

Maybe it's a dumb question... but reading the code I'm not able to see where the ENDPOINT is used.

Indeed, I can only found the endpoint = None, and self.endpoint = ....

Is this library yet finished or is still missing the conection with redsys?

I ask it, due to If y try to pass the parameters to Response() nothing is been stored.

Thank you

**Comment by ddiazpinto** [comment]
Hi @JustDevZero 
*Direct connection* (or webservice) client is not still developed. The only method you can actually use is the redirect connection method through `RedirectClient`.

Using the redirect connection method you are going to need a webserver to **redirect** the *user-agent* to the Redsys platform to finalize the payment step. The purpose of this library is to do not resolve this communication step and let the software of the webserver do it.

If you intend to use this library with Django, take a look at <https://github.com/ddiazpinto/django-redsys>. Django-redsys uses this library but extending the functionality to handle all the communication step through signals and views. Unfortunately it is not documented at all ;(.

I have updated the README of this library to explain all this things better.

Let me know if this resolves your question.
Thanks

**Comment by JustDevZero** [comment]
Hi @ddiazpinto 

I understand your idea and really appreciate your protips. But sadly I need the webservice/Direct conection due to the need to of a certain level of automation.

Anyway thanks for your efforts and  your time.

Consider the question solved ;)

**Comment by ddiazpinto** [comment]
Thank you ;)
